/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module xor_it(rst, clk, def_sig, change_defxor, data_in, custom_xor, new_def_xor, xored);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input change_defxor;
  wire change_defxor;
  input clk;
  wire clk;
  input [7:0] custom_xor;
  wire [7:0] custom_xor;
  input [7:0] data_in;
  wire [7:0] data_in;
  input def_sig;
  wire def_sig;
  input [7:0] new_def_xor;
  wire [7:0] new_def_xor;
  input rst;
  wire rst;
  output [7:0] xored;
  reg [7:0] xored;
  assign _01_ = new_def_xor[3] & change_defxor;
  assign _02_ = def_sig ? _01_ : custom_xor[3];
  assign _00_[3] = _02_ ^ data_in[3];
  assign _03_ = new_def_xor[4] | ~(change_defxor);
  assign _04_ = def_sig ? _03_ : custom_xor[4];
  assign _00_[4] = _04_ ^ data_in[4];
  assign _05_ = new_def_xor[5] & change_defxor;
  assign _06_ = def_sig ? _05_ : custom_xor[5];
  assign _00_[5] = _06_ ^ data_in[5];
  assign _07_ = new_def_xor[6] | ~(change_defxor);
  assign _08_ = def_sig ? _07_ : custom_xor[6];
  assign _00_[6] = _08_ ^ data_in[6];
  assign _09_ = new_def_xor[7] & change_defxor;
  assign _10_ = def_sig ? _09_ : custom_xor[7];
  assign _00_[7] = _10_ ^ data_in[7];
  assign _11_ = new_def_xor[0] | ~(change_defxor);
  assign _12_ = def_sig ? _11_ : custom_xor[0];
  assign _00_[0] = _12_ ^ data_in[0];
  assign _13_ = new_def_xor[1] & change_defxor;
  assign _14_ = def_sig ? _13_ : custom_xor[1];
  assign _00_[1] = _14_ ^ data_in[1];
  assign _15_ = new_def_xor[2] | ~(change_defxor);
  assign _16_ = def_sig ? _15_ : custom_xor[2];
  assign _00_[2] = _16_ ^ data_in[2];
  always @(posedge clk, posedge rst)
    if (rst) xored[0] <= 1'h0;
    else xored[0] <= _00_[0];
  always @(posedge clk, posedge rst)
    if (rst) xored[1] <= 1'h0;
    else xored[1] <= _00_[1];
  always @(posedge clk, posedge rst)
    if (rst) xored[2] <= 1'h0;
    else xored[2] <= _00_[2];
  always @(posedge clk, posedge rst)
    if (rst) xored[3] <= 1'h0;
    else xored[3] <= _00_[3];
  always @(posedge clk, posedge rst)
    if (rst) xored[4] <= 1'h0;
    else xored[4] <= _00_[4];
  always @(posedge clk, posedge rst)
    if (rst) xored[5] <= 1'h0;
    else xored[5] <= _00_[5];
  always @(posedge clk, posedge rst)
    if (rst) xored[6] <= 1'h0;
    else xored[6] <= _00_[6];
  always @(posedge clk, posedge rst)
    if (rst) xored[7] <= 1'h0;
    else xored[7] <= _00_[7];
endmodule
