/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "xor_it.v:3.1-22.10" *)
module xor_it(rst, clk, def_sig, change_defxor, data_in, custom_xor, new_def_xor, xored);
  (* src = "xor_it.v:12.1-19.4" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "xor_it.v:4.35-4.48" *)
  input change_defxor;
  wire change_defxor;
  (* src = "xor_it.v:4.21-4.24" *)
  input clk;
  wire clk;
  (* src = "xor_it.v:5.31-5.41" *)
  input [7:0] custom_xor;
  wire [7:0] custom_xor;
  (* src = "xor_it.v:5.22-5.29" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "xor_it.v:4.26-4.33" *)
  input def_sig;
  wire def_sig;
  (* src = "xor_it.v:5.43-5.54" *)
  input [7:0] new_def_xor;
  wire [7:0] new_def_xor;
  (* src = "xor_it.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "xor_it.v:6.22-6.27" *)
  output [7:0] xored;
  wire [7:0] xored;
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(rst),
    .Y(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _23_ (
    .A(custom_xor[3]),
    .SLEEP(def_sig),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(change_defxor),
    .B(def_sig),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a31oi_1 _25_ (
    .A1(new_def_xor[3]),
    .A2(change_defxor),
    .A3(def_sig),
    .B1(_09_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(data_in[3]),
    .B(_11_),
    .Y(_00_[3])
  );
  sky130_fd_sc_hd__o22ai_1 _27_ (
    .A1(def_sig),
    .A2(custom_xor[4]),
    .B1(_10_),
    .B2(new_def_xor[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(data_in[4]),
    .B(_12_),
    .Y(_00_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(custom_xor[5]),
    .SLEEP(def_sig),
    .X(_13_)
  );
  sky130_fd_sc_hd__a31oi_1 _30_ (
    .A1(change_defxor),
    .A2(def_sig),
    .A3(new_def_xor[5]),
    .B1(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(data_in[5]),
    .B(_14_),
    .Y(_00_[5])
  );
  sky130_fd_sc_hd__o22ai_1 _32_ (
    .A1(def_sig),
    .A2(custom_xor[6]),
    .B1(_10_),
    .B2(new_def_xor[6]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(data_in[6]),
    .B(_15_),
    .Y(_00_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _34_ (
    .A(custom_xor[7]),
    .SLEEP(def_sig),
    .X(_16_)
  );
  sky130_fd_sc_hd__a31oi_1 _35_ (
    .A1(change_defxor),
    .A2(def_sig),
    .A3(new_def_xor[7]),
    .B1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(data_in[7]),
    .B(_17_),
    .Y(_00_[7])
  );
  sky130_fd_sc_hd__o22ai_1 _37_ (
    .A1(def_sig),
    .A2(custom_xor[0]),
    .B1(_10_),
    .B2(new_def_xor[0]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(data_in[0]),
    .B(_18_),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _39_ (
    .A(custom_xor[1]),
    .SLEEP(def_sig),
    .X(_19_)
  );
  sky130_fd_sc_hd__a31oi_1 _40_ (
    .A1(change_defxor),
    .A2(def_sig),
    .A3(new_def_xor[1]),
    .B1(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(data_in[1]),
    .B(_20_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__o22ai_1 _42_ (
    .A1(def_sig),
    .A2(custom_xor[2]),
    .B1(_10_),
    .B2(new_def_xor[2]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(data_in[2]),
    .B(_21_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(rst),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(rst),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _46_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _47_ (
    .A(rst),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _48_ (
    .A(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _49_ (
    .A(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(rst),
    .Y(_08_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(xored[0]),
    .RESET_B(_01_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(xored[1]),
    .RESET_B(_02_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(xored[2]),
    .RESET_B(_03_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _54_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(xored[3]),
    .RESET_B(_04_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _55_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(xored[4]),
    .RESET_B(_05_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _56_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(xored[5]),
    .RESET_B(_06_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _57_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(xored[6]),
    .RESET_B(_07_)
  );
  (* src = "xor_it.v:12.1-19.4" *)
  sky130_fd_sc_hd__dfrtp_1 _58_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(xored[7]),
    .RESET_B(_08_)
  );
endmodule
